name: publish-packages
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  create_nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.SECRET_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ secrets.DOTNET_VERSION }}

      - name: Set Git Identity
        run: |
          git config --global user.email "vbardin810@gmail.com"
          git config --global user.name "Vladyslav Bardin"

      - name: Determine Version
        id: determine_version
        run: |
          if [ "$GITHUB_REF" == "refs/heads/main" ]; then
            # For commits to the main branch, update the minor version
            echo "minor"
          else
            # For commits within a PR, update the patch version
            echo "patch"
          fi

      - name: Update Version
        run: |
          version_type=${{ steps.determine_version.outputs.version }}
          dotnet pack ./Trumpee.MassTransit.Messages.csproj -c ${{ secrets.BUILD_CONFIGURATION }} -o output /p:VersionSuffix=-${{ github.run_number }}.${{ github.run_id }}.${version_type}

      - name: Commit Version Bump
        run: |
          git add **/*.csproj
          git commit -m "Bump version"
          git push
