name: Bump Patch Version on PR Commit

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Install dotnet-bump
        run: dotnet tool install --global dotnet-bump --version 1.0.1  # Replace with your desired version

      - name: Add dotnet tools to PATH
        run: echo "::add-path::$HOME/.dotnet/tools"

      - name: Determine Version
        id: determine_version
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "minor"
          else
            echo "patch"
          fi

      - name: Update Version
        run: |
          version_type=${{ steps.determine_version.outputs.version }}
          $GITHUB_WORKSPACE/.dotnet/tools/dotnet-bump/.dotnet/tools/dotnet-bump $version_type ./Trumpee.MassTransit.Messages.csproj
          git add ./Trumpee.MassTransit.Messages.csproj
          git commit -m "Bump $version_type version"
          git push
