name: Bump Patch Version on PR Commit

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.*

      - name: Install dotnet-bump
        run: dotnet tool install --global dotnet-bump

      - name: Determine Version
        id: determine_version
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "minor"
          else
            echo "patch"
          fi

      - name: Update Version
        run: |
          version_type=${{ steps.determine_version.outputs.version }}
          dotnet bump $version_type ./Trumpee.MassTransit.Messages.csproj
          git add ./YourProject.csproj  # Replace with your project file name
          git commit -m "Bump $version_type version"
          git push
