name: Bump Patch Version on PR Commit

on:
  push:
    branches-ignore:
      - main

jobs:
  bump_version:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Bump Version
        id: bump_version
        uses: SiqiLu/dotnet-bump-version@master
        with:
          version_mask: 0.0.0.1
          version_overwrite: "*.*.*.*"
          version_files: "./Trumpee.MassTransit.Messages.csproj"
          github_token: ${{ secrets.SECRET_TOKEN }}

      - name: Create NuGet Package
        run: dotnet pack "./Trumpee.MassTransit.Messages.csproj" -c Release -o nuget

      - name: Cache NuGet Package
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 1
          path: nuget/*.nupkg
    
  deploy:
    runs-on: ubuntu-latest
    needs: [ bump_version ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: nuget
          path: nuget

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish NuGet to GitHub package registry
        run: |
          foreach($file in (Get-ChildItem "nuget" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key "${{ secrets.SECRET_TOKEN }}" --source https://nuget.pkg.github.com/trumpee/index.json --skip-duplicate
          }