name: Bump Patch Version on PR Commit

on:
  push:
    branches-ignore:
      - main

jobs:
  bump_version:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Bump Version
        id: bump_version
        uses: SiqiLu/dotnet-bump-version@master
        with:
          version_mask: 0.0.0.1
          version_overwrite: "*.*.*.*"
          version_file: "./Trumpee.MassTransit.Messages.csproj"
          github_token: ${{ secrets.GITHUB_TOKEN }}
